server:
  port: 8083

spring:
  datasource:
    name: test
    url: jdbc:mysql://119.29.105.29:3306/gduf_scu?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: yIk9SmfP
    password: linjiayu0605
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  http:
    encoding:
      force: true

mybatis:
  mapper-locations: classpath:mapping/org/scu/*/mapper/*.xml
  config-locations: classpath:mybatis/mybatis-config.xml
  type-aliases-package: org.scu.*.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#logging:
#  config: classpath:logback.xml